### PR TITLE
Update requirements.yaml

### PR DESCRIPTION
**Pull request by siebrenf**
**What problem is the PR solving / What's new?**
should improve genome install speed & stability a bit

### CODE REVIEW

**Review by Maarten-vd-Sande — APPROVED** [review]
just be careful about the dependency stuff that pops up from it :)

**Comment by siebrenf** [comment]
genomepy 0.9.3 requires tqdm >= 4.49, 
pysradb (0.11.1) == 4.51. 

So now I'm updating some packages. The new pysradb should work nicely with genomepy, and the other changes are hotfix version upgrades anyway...

**Comment by siebrenf** [comment]
pysradb now returns `pd.NA` instead of "N/A". Apparently, working with `pd.NA` is a little tricky, cause pandas made a note of it in their docs. I found that out halfway through these commits :p

**Review by Maarten-vd-Sande — APPROVED** [review]
Seems fine :smile:

**Pull request merged**
