### PR TITLE
Update qc.smk

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
**What problem is the PR solving / What's new?**
A description of the problem that is being solved, or which new feature is implemented. Please link to other relevant issues/pr if relevant

**What did change**
Explain clearly and concisely what you changed. Why did you take certain design decisions?

**Checklist**
- [ ] I made a PR to develop (not master)
- [ ] If applicable: I updated the docs
- [ ] I updated the CHANGELOG
- [ ] These changes are covered by the tests

### CODE REVIEW

**Comment by siebrenf** [comment]
I removed that line in #896. Can this be closed?

**Comment by Maarten-vd-Sande** [comment]
@siebrenf I don't think it was removed?

**Comment by siebrenf** [comment]
image

**Comment by Maarten-vd-Sande** [comment]
Okay I am blind....

**Pull request closed without merging**
