### PR TITLE
Sc rna docs

### PR DESCRIPTION
**Pull request by tilschaef**
**What problem is the PR solving / What's new?**
Added documentation for scRNA workflow and examples.

**What did change**
Added documentation for scRNA workflow and examples.

**Checklist**
- [X] I made a PR to develop (not master)
- [ ] If applicable: I updated the docs
- [X ] I updated the CHANGELOG
- [ ] These changes are covered by the tests

### CODE REVIEW

**Review by Maarten-vd-Sande — APPROVED** [review]

**Comment by Maarten-vd-Sande** [comment]
docs can just go directly to master, which means they also get built immediatly. You do not have to add docs to the changelog. 

p.s. there are some newlines at the end of the file which should be removed.

**Review by siebrenf — APPROVED** [review]
I changed the target to Master, and removed the changelog changes as Maarten suggested.

**Comment by tilschaef** [comment]
Thanks for the info guys. It seems that I cannot merge the branch since it is protected and I am not authorized.

**Comment by Maarten-vd-Sande** [comment]
@tilschaef you should have permission now. These kinda PRs you should **Squash and Merge**

**Pull request merged**
