### PR TITLE
Fix#482

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
**What problem is the PR solving / What's new?**
See issue #482. 

**Checklist**
- [x] I made a PR to develop (not master)
- [x] If applicable: I updated the docs
- [x] I updated the CHANGELOG
- [x] These changes are covered by the tests

### CODE REVIEW

**Review by siebrenf — APPROVED** [review]

**Comment by siebrenf** [comment]
I did some test with the old `ruleorder` back in (and no constraints) and it _seemed_ to work fine (again):

```
ruleorder: macs2_callpeak > narrowpeak_summit
rule narrowpeak_summit:
    """
    Convert a narrowpeak file to a "macs2 summits" file.
    """
    input:
        get_peakfile_for_summit,
    output:
        expand("{result_dir}/{{peak_caller}}/{{assembly}}-{{sample}}_summits.bed", **config),
    log:
        expand("{log_dir}/narrowpeak_summit/{{sample}}-{{assembly}}-{{peak_caller}}.log", **config),
    benchmark:
        expand("{benchmark_dir}/narrowpeak_summit/{{sample}}-{{assembly}}-{{peak_caller}}.benchmark.txt", **config)[0]
    shell:
        """
        awk 'BEGIN {{OFS="\t"}} {{ print $1,$2+$10,$2+$10+1,$4,$9; }}' {input} > {output} 2> {log}
        """
```

The docs comment that ruleorder does work if the input of a rule was missing. So perhaps this was due to the other bugs :s

**Comment by Maarten-vd-Sande** [comment]
I thought before that it worked, however when I implemented it (already on master :scream: ) it failed.... But that still would be the best solution indeed!

https://github.com/vanheeringen-lab/seq2science/commit/4abd5070804dfe56a2a698c22b64f5f2379c5ecb

I can not find this in the docs:

> The docs comment that ruleorder does work if the input of a rule was missing. 

But that could indeed be the problem then.

p.s. tests are running 14 hours already :shrug:

**Comment by siebrenf** [comment]
It's not listed with the wildcards, but with the [ambiguous rules sections](https://snakemake.readthedocs.io/en/latest/snakefiles/rules.html#snakefiles-ambiguous-rules). 

I have no clue about Jenkins. Have you tried turning it off and on again? :p

**Comment by Maarten-vd-Sande** [comment]
I restarted my pc, lets see.

> e.g. due to missing input files

I think this does not mean inputerrors?

**Pull request closed without merging**
