### PR TITLE
WIP: Unicode error

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
**What problem is the PR solving / What's new?**
A description of the problem that is being solved, or which new feature is implemented. Please link to other relevant issues/pr if relevant

**What did change**
Explain clearly and concisely what you changed. Why did you take certain design decisions?

**Checklist**
- [ ] I made a PR to develop (not master)
- [ ] If applicable: I updated the docs
- [ ] I updated the CHANGELOG
- [ ] These changes are covered by the tests

### CODE REVIEW

**Comment by siebrenf** [comment]
the unicode error is in snakemake. Same error in both of there runs:

http://ocimum.science.ru.nl/jenkins/blue/organizations/jenkins/seq2science/detail/PR-500/1/pipeline
http://ocimum.science.ru.nl/jenkins/blue/organizations/jenkins/seq2science/detail/ruleorder_rename_fastq/1/pipeline
```
  File "/var/lib/jenkins/workspace/q2science_ruleorder_rename_fastq/miniconda/envs/s2s/lib/python3.6/site-packages/snakemake/deployment/conda.py", line 324, in create

    logger.debug(out.decode())

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 29380: invalid continuation byte

```


test run snakemake=5.18.1. The next version (5.19.0), has the following change to line 324:
```
             -   logger.debug(out.decode())
             +   logger.debug(out)
```

I suggest to try 5.19.3 (last hotfix of that version).

**Comment by Maarten-vd-Sande** [comment]
I am not entirely sure if it is related to the snakemake version. The current version change fixes the error. However seq2science fails in the actual run:
http://ocimum.science.ru.nl/jenkins/blue/organizations/jenkins/seq2science/detail/unicode_error/5/pipeline

**Comment by Maarten-vd-Sande** [comment]
Plus last time we updated snakemake everything started exploding :angel:

**Comment by siebrenf** [comment]
my hypothesis is that in snakemake/deployment/conda.py, conda is returning that latin1 symbol while installing chipseeker, which snakemake then cannot decode. In this situation, changing the chipseeker version fixes the issue, but not the reason it went wrong. 

You could revert the chipseeker version and see if everything works again :)

**Comment by siebrenf** [comment]
> 
> 
> Plus last time we updated snakemake everything started exploding 👼

yes, I am also afraid this may happen. this is why I updated to 5.19, and not to latest :s

**Review by siebrenf — APPROVED** [review]

**Pull request merged**
