### PR TITLE
Update macs2.yaml

### PR DESCRIPTION
**Pull request by siebrenf**
**Checklist**
- [x] I made a PR to develop (not master)
- [ ] If applicable: I updated the docs
- [ ] I updated the CHANGELOG
- [ ] These changes are covered by the tests

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
That is really strange... On which system did this fail? I haven't had any issues with this... :detective: 50.3.1 does exists, however it shouldn't matter which one of those we use. The V part is bothering me :P

I don't know what is causing the tests to fail... I will take a look tomorrow

**Comment by Maarten-vd-Sande** [comment]
Installation with conda or mamba?

**Review by Maarten-vd-Sande — APPROVED** [review]

**Comment by JGASmits** [comment]
Is this solving the error:

CreateCondaEnvironmentException:
Could not create conda environment from /ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/seq2science/seq2science/rules/../envs/macs2.yaml:
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

ResolvePackageNotFound:
  - anaconda::setuptools=v50.3.1


  File "/vol/mbconda/jsmits/envs/s2s_js_test/lib/python3.6/site-packages/snakemake/deployment/conda.py", line 335, in create
?

Because I just ran into that one generating a Macs2.yaml package :)

**Comment by JGASmits** [comment]
I am now running it on the branch "siebrenf-patch-1" to check if it is fixed!

**Comment by JGASmits** [comment]
Running it on the "siebrenf-patch-1", fixes the issue with the MACS2.yaml error. 

👍

**Comment by siebrenf** [comment]
huh, didnt see these comment before Jos' remark somehow. Sorry @Maarten-vd-Sande !

Dick had this issue. To recreate, just try `conda search anaconda::setuptools` or `mamba search anaconda::setuptools`. Both the "v" and the hotfix .1 are not found...

**Comment by Maarten-vd-Sande** [comment]
Let's merge this? :)

**Pull request merged**
