### PR TITLE
Explain qc

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
**What problem is the PR solving / What's new?**
Related to #664 to make it more clear what we are doing. 

**todo**

- [ ] @siebrenf, is this approach okay/maintainable enough? I'm not sure how else, `_explain` isn't easier I think...
- [ ] Better explain tests, there were some errors introduced and tests passed :see_no_evil: 
- [ ] Not sure how easy/possible it is to make hyperlinks. Much nicer to read actually.
- [ ] Add explanation to FAQ what the final bam is

image

**Checklist**
- [x] I made a PR to develop (not master)
- [ ] If applicable: I updated the docs
- [ ] I updated the CHANGELOG
- [x] These changes are covered by the tests

### CODE REVIEW

**Comment by siebrenf** [comment]
The explain feature is neat, and this would be another way of bringing this feature info to the user. 
However, it is a wall of text. I'm not sure if it would be read more than the explain function itself this way.

What you could do is add the explain to the bottom of the multiQC, and add a link/verbal reference in it in the BAM QC section header.

**Comment by Maarten-vd-Sande** [comment]
It does not only relate to the BAM stuff. So I am not sure about linking it in the bam qc section. Another thing is that I am afraid when we put it on the bottom, that people (again) won't read it. Maybe I can make hyperlinks instead of those urls in brackets. But not sure how that would translate on the terminal

**Comment by Maarten-vd-Sande** [comment]
@siebrenf and if I were to make each url a hyperlink? No hyperlink here, but the text is much nicer to read already (and shorter)
image

**Comment by siebrenf** [comment]
You could drop all references here, and refer to the explain function. Additionally, some text from the explain feature can be shortened (removing `with options ""` if there are none). Together the explain text might get small and readable enough :)

btw, explain tests are now working & expanded in the develop branch again

**Comment by siebrenf** [comment]
its actually not that much work. Ill test it out!

**Comment by Maarten-vd-Sande** [comment]
Cool, because I like what you proposed. Much more consistent

**Review by siebrenf — APPROVED** [review]
on the TODOs:
- the various explain methods should be easier to read without the regex. maintainability ✔️ 
- explain tests were fixed prior: ✔️ 
- sweet hyperlink functionality: ✔️ 
- final BAM is now sort-of explained in the sieve-bam rule: 🤷

**Comment by Maarten-vd-Sande** [comment]
We would need to up the minimum python version for the walrus btw

**Pull request merged**
