### PR TITLE
same condition across assemblies

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
**What problem is the PR solving / What's new?**
I want to be able to specify a samples.tsv like this

```
sample  assembly        condition       
GSM2942627      ASM20922v1      polyp
GSM2942628      ASM20922v1      polyp
GSM2837480      Bl71nemr        polyp
GSM2837481      Bl71nemr        polyp
```

**What did change**
Explain clearly and concisely what you changed. Why did you take certain design decisions?

**Checklist**
- [x] I made a PR to develop (not master)
- [x] If applicable: I updated the docs
- [x] I updated the CHANGELOG
- [x] These changes are covered by the tests

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
What a coincidence, @qxuchn reports he gets it with this samples file

```
sample	assembly	condition	descriptive_name	control
SRR4011697	xt10.0	st8_Foxh1	st8_Foxh1_rep1	GSM2263598
SRR4011696	xt10.0	st8_Foxh1	st8_Foxh1_rep2	GSM2263598
SRR4011699	xt10.0	st9_Foxh1	st9_Foxh1_rep1	GSM2263600
SRR4011698	xt10.0	st9_Foxh1	st9_Foxh1_rep2	GSM2263600
SRR4011709	xt10.0	st10.25_Foxh1	st10.25_Foxh1_rep1	GSM1298094
GSM1298090	xt10.0	st10.5_Foxh1	st10.5_Foxh1_rep1	GSM1298094
GSM1298091	xt10.0	st10.5_Foxh1	st10.5_Foxh1_rep2	GSM1298094 
```

**Comment by Maarten-vd-Sande** [comment]
Seems that this check was overly cautious. Was added recently here:
https://github.com/vanheeringen-lab/seq2science/commit/69b1c6643f578083489bf6e2e3ea302087600f16

Quan and I seem to have no problems with this removed

**Comment by siebrenf** [comment]
Won't this cause issues when doing a lookup in `breps` before filtering for assembly?

I had a look around, and it might cause issues in
- peak calling, line 33
- trackhub, line 280

If it doesn't, I'm good with removing it!

**Comment by Maarten-vd-Sande** [comment]
I think you are right. I checked macs2 and some DAGs and it seemed safe. Good catch!

**Comment by Maarten-vd-Sande** [comment]
I am not sure what wouldn't work in the trackhub?

**Comment by Maarten-vd-Sande** [comment]
These bigpeaks get added:

/home/maarten/Desktop/seq2science/results/macs2/ASM20922v1-polyp.bignarrowPeak
/home/maarten/Desktop/seq2science/results/macs2/Bl71nemr-polyp.bignarrowPeak

**Comment by siebrenf** [comment]
If I got it correctly, in line 285 `expand(f"{{result_dir}}/{peak_caller}/{brep['assembly']}-{sample}.big{ftype}", **config)`, `brep['assembly']` would return a list, not a string.

**Comment by Maarten-vd-Sande** [comment]
Something to do after the holidays :palm_tree: :sun_with_face:

**Comment by Maarten-vd-Sande** [comment]
@siebrenf I believe the trackhub part should still work, but I fixed the genrich bug :). Ready for re-review

**Pull request merged**
