### PR TITLE
Brep fix

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
**What problem is the PR solving / What's new?**
A description of the problem that is being solved, or which new feature is implemented. Please link to other relevant issues/pr if relevant

**What did change**
Explain clearly and concisely what you changed. Why did you take certain design decisions?

**Checklist**
- [ ] I made a PR to develop (not master)
- [ ] If applicable: I updated the docs
- [ ] I updated the CHANGELOG
- [ ] These changes are covered by the tests

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
Oh that is interesting! These lines definitely change the behaviour. I'll take a look :detective:

**Comment by siebrenf** [comment]
now that I look at it, perhaps it goes wrong if you have both replicates and conditions...

fix:
```
if samples['condition'].tolist() == samples['sample'].tolist() or config.get('biological_replicates') == 'keep':
```
should maybe be
```
col = 'replicate' if 'replicate' in samples else 'sample'
if samples['condition'].tolist() == samples[col].tolist() or config.get('biological_replicates') == 'keep':
```

**Comment by Maarten-vd-Sande** [comment]
col = 'replicate' if 'replicate' in samples and config.get('technical_replicates', 'keep') ~- keep else 'sample'

**Comment by Maarten-vd-Sande** [comment]
Never mind, that column gets deleted in the lines before

**Comment by Maarten-vd-Sande** [comment]
I am leaving this one here to consider with #600

**Review by siebrenf — APPROVED** [review]
only 1 change required in #600 to make this compatible.

**Pull request merged**
