### PR TITLE
Update get_genome_annotation.py

### PR DESCRIPTION
**Pull request by siebrenf**
**What problem is the PR solving / What's new?**
A description of the problem that is being solved, or which new feature is implemented. Please link to other relevant issues/pr if relevant

**What did change**
Explain clearly and concisely what you changed. Why did you take certain design decisions?

**Checklist**
- [x] I made a PR to develop (not master)
- [ ] If applicable: I updated the docs
- [ ] I updated the CHANGELOG
- [ ] These changes are covered by the tests

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
I am not sure if this is the cause of the problem. I think it happens because genomepy has trouble connecting to some server(s)

https://github.com/vanheeringen-lab/genomepy/blob/master/genomepy/provider.py#L72

**Comment by siebrenf** [comment]
I might have mixed up the two errors we've been having with this section. 

That said, this error message will only display if the rules run, and while running, are requested to download from an unsupported provider. So it might still help with that other issue...

**Comment by Maarten-vd-Sande** [comment]
I usually avoid `seq2science clean` since it also removes all the installed environments, and that takes quite some time. :upside_down_face:

**Comment by siebrenf** [comment]
fair. we could instead delete the genomepy pickle in this if-statement, and provide explanation. I'll make something better when I have the time :)

**Comment by Maarten-vd-Sande** [comment]
No, that will introduce lots of edge-case bugs (e.g. downloading multiple genomes). Please don't! :yum: 

I don't think I ever had problems with a corrupted genomepy+seq2science cache.

**Comment by Maarten-vd-Sande** [comment]
@siebrenf maybe something like this? This also should not print the exception anymore, it should just add it to the log (as it is supposed to do)

**Review by Maarten-vd-Sande — APPROVED** [review]
very good, the smartest solution, only the best :+1:

**Pull request merged**
