### PR TITLE
expanded DAG tests for alignment. others WIP.

### PR DESCRIPTION
**Pull request by siebrenf**
**What problem is the PR solving / What's new?**
Our workflow is complex. This means many edge-cases can arise.
Testing a build is cumbersome, since it relies on Jenkins and uploading to git.
This PR takes the DAG tests out of Jenkins, and into a shell script that can be executed locally.
With this we can test the logic connecting rules much more easily, and more thoroughly.

**What did change**
DAG tests are taken from the Jenkinsfile and placed in dag_tests.sh. 
This script will be called by the Jenkinsfile
DAG tests are expanded to include more logic (replicates, conditions, etc.)

Between tests, files are touched to reduce the complexity of the DAG where possible without compromising the complexity of the test (e.g. bam files are touched after alignment tests are completed)

**Does this need additional test(s)?**
I AM THE ONE WHO TESTS!

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
Really nice! Is the idea that we call this script in the Jenkinsfile? Or that we keep them separate?

**Comment by Maarten-vd-Sande** [comment]
P.s. installing conda takes really long at the moment. Can I ask you to take a look at this? :angel:

**Comment by siebrenf** [comment]
This will eventually be called in Jenkins, yes!

btw, the method is already finding the edge-cases I was talking about. Quite a few steps (QC reports and trackhubs) break when using >1 assembly. I hope I can find the issues before the transfer to seq2science.

**Comment by siebrenf** [comment]
the script (so far) is working, yay!

**Comment by Maarten-vd-Sande** [comment]
@siebrenf please ping me when it's ready for review.

**Pull request closed without merging**
