### PR TITLE
multiqc 1.10

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
**What problem is the PR solving / What's new?**
I added macs2 number of peaks in a narrowpeak file to multiqc, and this has now been released :tada:. Unfortunately the scRNA QC PR was not yet merged (https://github.com/ewels/MultiQC/pull/1341), so that will happen later.

**Checklist**
- [x] I made a PR to develop (not master)
- [ ] If applicable: I updated the docs
- [ ] I updated the CHANGELOG
- [x] These changes are covered by the tests

### CODE REVIEW

**Review by siebrenf — APPROVED** [review]
why split fastqc and multiqc? Considering their contents it may cause more hassle (fastqc needs to be updated in 2 places)

**Comment by Maarten-vd-Sande** [comment]
Since we have also have `fastp` as a (default) trimmer. This means we install something that isn't used most of the time

**Comment by Maarten-vd-Sande** [comment]
Also not sure how e.g. `gimmemotifs.coverage_table` works with those "unfiltered" bams

**Comment by Maarten-vd-Sande** [comment]
@siebrenf I see that it's still in the multiqc yaml! :zipper_mouth_face:

**Pull request merged**
