### PR TITLE
spike in support for scRNA

### LINKED ISSUE #617: Q: How to set-up custom genome indexes (with the scRNA-seq pipeline)?
**Question**
Trying to generate a genome with custom additions 1. unsure where to place the settings for this in the config.yaml and 2. custom additions are not getting incorporated, not sure where to look for troubleshooting? 
**Subquestion:** Is the custom addition also possible with multiple files? (e.g. If I seperate 2 .fa/.gtf files with spaces?)

**What have I tried**
- The pipeline overall seems to run really nice! :) The problem starts with adding the custom .fa/.gtf files.
- See below my .config.yaml, I tried placing the `custom_genome_extension:`, `custom_annotation_extension:`, `custom_assembly_suffix:`, also right below the `fastq_dir:`-setting, although then the program is in trouble to locate my fastq files. Therefore, I now put it right before the `ref:`-settings, where the index-settings are stored.
- The picture below does show that the settings are saved.
- My output genome files don't seem to incorporate the additions (ERCC and reporter genes). This might also still be a Kallisto | Bustools related issue (although the genome-additions are set-up in such a way, that in an isolated KB-workflow these files worked with building the index!).
- I tried with and without setting the `custom_assembly_suffix:`.
- The pipeline is able to run normally, I cannot trace back any of my added genes in my genome files (e.g. GRCh38_t2g.txt, listing all the genes included in the index)

My config.yaml:
```
# tab-separated file of the samples
samples: samples.tsv

# pipeline file locations
result_dir: ./results  # where to store results
genome_dir: ./genomes  # where to look for or download the genomes
fastq_dir: ../data/CMdiff_mon-EB-EHT_d4-26_all # where to look for fastqs

# contact info for multiqc report and trackhub
email: r.snabel@science.ru.nl

# how to handle replicates
technical_replicates: merge

# scRNA options
# seq2science does currently not support scrna-seq platforms that generate more than two fastq files, such as 10xv1.
quantifier:
  kallistobus:
    ## Quantification example ##
    #count: '-x 0,8,16:0,0,8:1,0,0 --h5ad --verbose'
    #count: '-x 10XV3 --h5ad --verbose'

    ## Velocity example ##
    custom_genome_extension: ./genome_addons/ERCC92_reporter.fa
    custom_annotation_extension: ./genome_addons/ERCC92_reporter_biotype.gtf
    custom_assembly_suffix: "_ERCC_reporter"

    ref: '--workflow lamanno'
    count: '-x 0,8,16:0,0,8:1,0,0 --h5ad --verbose --workflow lamanno'
    #count: '-x 0,8,16:0,0,8:1,0,0 --h5ad --verbose --workflow lamanno'
    #count: '-x 10XV3 --verbose --h5ad --workflow lamanno'

barcodefile: "../1col_barcode_384.tab"
```
Output after running: 
afbeelding

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
**What problem is the PR solving / What's new?**
Fix #617 

**Checklist**
- [x] I made a PR to develop (not master)
- [x] If applicable: I updated the docs
- [x] I updated the CHANGELOG
- [ ] These changes are covered by the tests

### CODE REVIEW

**Review by siebrenf — APPROVED** [review]
Oh wow I forgot to make _custom a variable that often?

**Comment by Maarten-vd-Sande** [comment]
@Rebecza can you try if this works?

Install with:

```
pip install git+https://github.com/vanheeringen-lab/seq2science@spike-ins-scRNA
```

**Comment by Maarten-vd-Sande** [comment]
> Oh wow I forgot to make _custom a variable that often?

bad review :see_no_evil:

**Comment by Rebecza** [comment]
Now this works, thanks! :)

**Pull request merged**
