### PR TITLE
Correlation_plot as png

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
Currently WIP. 

Can't collapse different contents: http://ocimum.science.ru.nl/multiqc/multiqc_report.html

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
This is still relevant. I am hoping/waiting for a new release of multiqc where I can collapse custom content and modules together. Phil Ewels (the maintainer) thought this was already possible.

This would be nice so I can put the correlation plots together in the deeptools section.

**Comment by Maarten-vd-Sande** [comment]
Now replaces the not-clustered interactive heatmaps with clustered non-interactive images

image

**Comment by Maarten-vd-Sande** [comment]
p.s. I gave up waiting for dendrogram support in multiqc :upside_down_face:

**Comment by Maarten-vd-Sande** [comment]
p.p.s. I should do the colors the other way around!

**Comment by Maarten-vd-Sande** [comment]
@siebrenf this is ready for review

**Review by siebrenf — APPROVED** [review]
Nice! 
Maybe the RNA-seq correlation plot can go with this in, but I'll compare the two later.

**Comment by Maarten-vd-Sande** [comment]
What do you mean? The order of the image? I can do that.

This is based on pileup over the genome. Not sure how useful, it just gives a general overview. Once differential peaks has been implemented, we should add these plots for the peaks as well, since that is a much more obvious way of calculating it.

**Pull request merged**
